id: IC2BC7116
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T12:20:43+00:00'
last_modified: '2022-06-07T18:46:41.946554+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17767
  title: ཛམ་དཀར་གཏེར་སྒྲུབ་བསྡུས་པ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EF32:
      image_group_id: I8LS17789
      title: ''
      total_pages: 182
      order: 1
      base_file: EF32.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
