id: P003272
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:51:46.879000
source_metadata:
  id: bdr:W8LS17767
  title: ཛམ་དཀར་གཏེར་སྒྲུབ་བསྡུས་པ་སོགས།
  author: ''
  volumes:
    527c00293019480b912e56abc2c21bff:
      image_group_id: I8LS17789
      title: ''
      volume_number: 1
      total_pages: 182
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
