id: P003272
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17767
  title: ཛམ་དཀར་གཏེར་སྒྲུབ་བསྡུས་པ་སོགས།
  author: ''
  volumes:
    527c00293019480b912e56abc2c21bff:
      image_group_id: I8LS17789
      title: ''
      volume_number: 1
      total_pages: 182
